touchpad:
  buttonpad: false
  gestures:

    #traverse open windows / global
    - type: swipe
      fingers: 3
      direction: left_right
      speed: slow

      actions:
        - on: begin
          input:
            - keyboard: [ +leftalt, tab ]

        - on: update
          interval: -75
          input:
            - keyboard: [ leftshift+tab ]

        - on: update
          interval: 75
          input:
            - keyboard: [ tab ]

        - on: end_cancel
          input:
            - keyboard: [ -leftalt ]

    # Show Overview / global
    - type: swipe
      fingers: 3
      direction: up

      actions:
        - on: begin
          plasma_shortcut: kwin,Overview

    # Show Desktop / global
    - type: swipe
      fingers: 3
      direction: down

      actions:
        - on: begin
          plasma_shortcut: kwin,Show Desktop

    # Next Song / global
    # - type: swipe
    #   fingers: 4
    #   direction: up
    #
    #   actions:
    #     - on: begin
    #       input:
    #         - keyboard: [ nextsong ]

    # Maximize Window / global
    - type: pinch
      fingers: 3
      direction: out

      actions:
        - plasma_shortcut: kwin,Window Maximize

    # Minimize Window / global
    - type: pinch
      fingers: 3
      direction: in

      actions:
        - plasma_shortcut: kwin,Window Minimize

    # Previous Song / global
    - type: swipe
      fingers: 4
      direction: down

      actions:
        - on: begin
          input:
            - keyboard: [ previoussong ]

    # mute / global
    - type: press
      fingers: 4

      actions:
        - on: begin
          input:
            - keyboard: [ playpause ]

